/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BRApplianceProtocol-Protocol.h"

@class NSBundle;

/// \addtogroup BackRow

/// \ingroup BackRow
@interface BRAppliance : NSObject <BRApplianceProtocol>
{
    NSBundle *_myBundle;
}

- (id)initWithSettings:(id)fp8;
- (void)dealloc;
- (id)version;
- (id)applianceKey;
- (id)applianceName;
- (float)applianceIconReflectionOffset;
- (float)applianceIconHorizontalOffset;
- (float)applianceIconKerningFactor;
- (id)applianceController;

@end

