/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BRMenuController.h"

@class BRCenteredMenuLayoutManager, BRTextControl;

/// \addtogroup BackRow

/// \ingroup BackRow
@interface BRCenteredMenuController : BRMenuController
{
    BRCenteredMenuLayoutManager *_layoutManager;
    BRTextControl *_primaryTextControl;
    BRTextControl *_secondaryTextControl;
    BRTextControl *_labelControl;
}

- (id)init;
- (void)dealloc;
- (void)setTitle:(id)fp8;
- (void)setIcon:(id)fp8 horizontalOffset:(float)fp12 kerningFactor:(float)fp16;
- (void)setPrimaryInfoText:(id)fp8;
- (void)setPrimaryInfoText:(id)fp8 withAttributes:(id)fp12;
- (void)setSecondaryInfoText:(id)fp8;
- (void)setSecondaryInfoText:(id)fp8 withAttributes:(id)fp12;
- (void)setLabel:(id)fp8;
- (void)setLabel:(id)fp8 withAttributes:(id)fp12;
- (void)setMenuWidthFactor:(float)fp8;

@end

