/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BRPanel.h"

@class BRControllerStack, NSMutableDictionary;

/// \addtogroup BackRow

/// \ingroup BackRow
@interface BRController : BRPanel
{
    NSMutableDictionary *_labels;
    BRControllerStack *_stack;
}

- (id)init;
- (void)dealloc;
- (id)description;
- (struct CGRect)controllerFrame;
- (void)setStack:(id)fp8;
- (id)stack;
- (BOOL)firstResponder;
- (void)addLabel:(id)fp8;
- (void)removeLabel:(id)fp8;
- (BOOL)isLabelled:(id)fp8;
- (BOOL)isNetworkDependent;
- (BOOL)isParentalControlsPasscodeRequired:(id *)fp8;
- (BOOL)popsOnBury;

@end

