/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

/// \addtogroup BackRow

/// \ingroup BackRow
@protocol BREventResponder
- (BOOL)brEventAction:(id)fp8;
@end

