/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@class BREvent, NSMutableArray, NSTimer;
//<BREventResponder>, 

/// \addtogroup BackRow

/// \ingroup BackRow
@interface BREventManager : NSObject
{
    NSObject<BREventResponder> *_firstResponder;
    BREvent *_currentEvent;
    NSTimer *_retriggerTimer;
    NSTimer *_blockingTimer;
    NSMutableArray *_eventQueue;
    struct __CFRunLoopSource *_source;
    struct __CFRunLoop *_runLoop;
    unsigned int _dumpWhenUnblocked:1;
    unsigned int _eventsBlocked:1;
    unsigned int _handlingEvent:1;
    double _flushBeforeTimeStamp;
}

+ (id)sharedManager;
- (id)init;
- (void)dealloc;
- (void)setFirstResponder:(id)fp8;
- (id)firstResponder;
- (void)blockEventsForTime:(double)fp8 dumpWhenFinished:(BOOL)fp16;
- (BREvent*)currentEvent;
- (void)postEvent:(id)fp8;
- (void)dispatchEventOnEventThread:(id)fp8;
- (void)emptyQueue;
- (void)retriggerCurrentEvent;
- (void)retriggerCurrentEventAfterDelay:(double)fp8;
- (void)cancelRetriggerCurrentEvent;

@end

