/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@interface BRImage : NSObject
{
    struct CGImage *_image;
}

+ (id)imageWithURL:(id)fp8;
+ (id)imageWithPath:(id)fp8;
+ (id)imageWithData:(id)fp8;
+ (id)imageWithCIImage:(id)fp8;
+ (id)imageWithPDFURL:(id)fp8;
+ (id)imageWithCGImageRef:(struct CGImage *)fp8;
- (id)initWithCGImageRef:(struct CGImage *)fp8;
- (void)dealloc;
- (id)downsampledImageForMaxSize:(struct CGSize)fp8;
- (id)mapImageWithSourceRect:(struct CGRect)fp8 toSize:(struct CGSize)fp24;
- (struct CGRect)largestSquareRect;
- (struct CGImage *)image;
- (struct CGSize)pixelBounds;
- (BOOL)isPowerOfTwo;
- (float)aspectRatio;
- (void)drawImageInContext:(struct CGContext *)fp8 rect:(struct CGRect)fp12;

@end

