/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol BRImageProvider <NSObject>
- (id)imageID;
- (void)registerAsPendingImageProvider:(id)fp8;
- (void)loadImage:(id)fp8;
@end

