/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BRControl.h"

@class BRListLayer, NSMutableArray, NSTimer;

/// \addtogroup BackRow

/// \ingroup BackRow
@interface BRListControl : BRControl
{
    id <BRMenuListItemProvider> _source;
    BRListLayer *_list;
    NSTimer *_pokeTimer;
    NSTimer *_delayTimer;
    NSTimer *_repeatTimer;
    double _repeatStart;
    double _repeatAccumulator;
    long _sourceItemCount;
    float _defaultHeight;
    long _savedSelection;
    NSMutableArray *_dividers;
    long _firstDividerIndex;
    long _lastDividerIndex;
}

- (id)init;
- (void)dealloc;
- (id)layer;
- (BOOL)brEventAction:(id)fp8;
- (void)setDatasource:(id)fp8;
- (id)datasource;
- (void)addDividerAtIndex:(long)fp8 withLabel:(id)fp12;
- (void)removeDividerAtIndex:(long)fp8;
- (void)removeDividers;
- (void)reload;
- (void)setSelection:(long)fp8;
- (long)selection;
- (id)axSelectedItemText;
- (float)listHeightToMaximum:(float)fp8;
- (void)setDisplaysSelectionWidget:(BOOL)fp8;
- (BOOL)displaysSelectionWidget;
- (void)setShowsWidgetBackingLayer:(BOOL)fp8;
- (BOOL)showsWidgetBackingLayer;
- (void)setLastItemCentered:(BOOL)fp8;
- (BOOL)lastItemCentered;
- (void)controlWillDeactivate;
- (id)visibleRowsAndRange:(struct _NSRange *)fp8;

@end

