/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@interface BRMediaPreviewControllerFactory : NSObject
{
}

+ (id)previewControlForAsset:(id)fp8 withDelegate:(id)fp12;
+ (id)previewControlForImageProvider:(id)fp8 withDelegate:(id)fp12;
+ (id)previewControlForAssets:(id)fp8 withDelegate:(id)fp12;
+ (id)previewControlForImageProviders:(id)fp8 withDelegate:(id)fp12;

@end

