/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BRType.h"

/// \addtogroup BackRow

/// \ingroup BackRow
@interface BRMediaType : BRType
{
    BRMediaType *_derivedFrom;
}

+ (void)initialize;
+ (id)song;
+ (id)songPreview;
+ (id)cdSong;
+ (id)musicVideo;
+ (id)musicVideoPreview;
+ (id)podcast;
+ (id)movie;
+ (id)dvd;
+ (id)moviePreview;
+ (id)TVShow;
+ (id)TVShowPreview;
+ (id)audioBook;
+ (id)movieTrailer;
+ (id)ytVideo;
+ (id)booklet;
+ (id)interactiveBooklet;
+ (id)coachedAudio;
+ (id)photo;
+ (id)stingrayMovie;
+ (id)httpAudioStream;
- (void)dealloc;
- (void)setParentType:(id)fp8;
- (id)parentType;

@end

