/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BRImageProvider-Protocol.h"

@protocol BRMediaAsset <BRImageProvider>
- (id)provider;
- (id)assetID;
- (id)title;
- (id)titleForSorting;
- (id)artist;
- (id)artistForSorting;
- (id)mediaSummary;
- (id)mediaDescription;
- (id)publisher;
- (id)composer;
- (id)composerForSorting;
- (id)copyright;
- (float)userStarRating;
- (void)setUserStarRating:(float)fp8;
- (float)starRating;
- (id)rating;
- (long)performanceCount;
- (void)incrementPerformanceCount;
- (void)incrementPerformanceOrSkipCount:(unsigned int)fp8;
- (BOOL)hasBeenPlayed;
- (void)setHasBeenPlayed:(BOOL)fp8;
- (long)duration;
- (id)mediaURL;
- (id)previewURL;
- (BOOL)hasCoverArt;
- (id)coverArtID;
- (id)thumbnailArtID;
- (BOOL)isProtectedContent;
- (id)playbackRightsOwner;
- (id)coverArt;
- (id)thumbnailArt;
- (id)coverArtForBookmarkTimeInMS:(unsigned int)fp8;
- (id)mediaUTI;
- (id)mediaType;
- (BOOL)hasVideoContent;
- (BOOL)isDisabled;
- (id)collections;
- (id)primaryCollection;
- (id)primaryCollectionTitle;
- (int)primaryCollectionOrder;
- (int)physicalMediaID;
- (id)seriesName;
- (id)seriesNameForSorting;
- (id)broadcaster;
- (id)episodeNumber;
- (unsigned int)season;
- (unsigned int)episode;
- (id)genres;
- (id)primaryGenre;
- (id)cast;
- (id)producers;
- (id)directors;
- (id)dateAcquired;
- (id)dateAcquiredString;
- (id)datePublished;
- (id)datePublishedString;
- (void)setBookmarkTimeInMS:(unsigned int)fp8;
- (void)setBookmarkTimeInSeconds:(unsigned int)fp8;
- (unsigned int)bookmarkTimeInMS;
- (unsigned int)bookmarkTimeInSeconds;
- (unsigned int)startTimeInMS;
- (unsigned int)startTimeInSeconds;
- (unsigned int)stopTimeInMS;
- (unsigned int)stopTimeInSeconds;
- (id)resolution;
- (BOOL)canBePlayedInShuffle;
- (BOOL)isLocal;
- (id)coverArtNoDefault;
- (void)skip;
- (id)authorName;
- (id)keywords;
- (id)viewCount;
- (id)category;
- (BOOL)isInappropriate;
- (int)grFormat;
- (void)willBeDeleted;
@end

