/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol BRMenuItemLayer <NSObject>
- (void)highlight;
- (void)unHighlight;
- (void)scrollItemIfNecessary;
- (void)stopScrollingItem;
- (struct CGRect)frameForCellBounds:(struct CGSize)fp8;
- (id)axItemText;
@end

