/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class BRRenderDisplayLink;

/// \addtogroup BackRow

/// \ingroup BackRow
@interface BRRenderer : NSObject
{
    BRRenderDisplayLink *_link;
}

- (void)dealloc;
- (void)orderOut;
- (void)orderIn;
- (void)displayOnline;
- (void)displayOffline;
- (unsigned int)createDVDWindow;
- (void)destroyDVDWindow:(unsigned int)fp8;
- (void)showDVDWindow:(unsigned int)fp8;
- (void)hideDVDWindow:(unsigned int)fp8;

@end

