/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BRSingleton.h"

@class BRIPConfiguration;

/// \addtogroup BackRow

/// \ingroup BackRow
@interface BRSettingsFacade : BRSingleton
{
    BRIPConfiguration *_ipConfiguration;
}

+ (id)singleton;
+ (void)setSingleton:(id)fp8;
- (id)init;
- (void)dealloc;
- (void)resetAllSettings;
- (void)refresh;
- (void)flushDiskChanges;
- (id)resolution;
- (BOOL)UISoundsEnabled;
- (void)setUISoundsEnabled:(BOOL)fp8;
- (BOOL)networkActive;
- (BOOL)videoClosedCaptionEnabled;
- (void)setVideoClosedCaptionEnabled:(BOOL)fp8;
- (int)musicRepeatMode;
- (void)setMusicRepeatMode:(int)fp8;
- (int)audioFormat;
- (void)setAudioFormat:(int)fp8;
- (BOOL)screenSaverEnabled;
- (void)setScreenSaverEnabled:(BOOL)fp8;
- (BOOL)screenSaverAllowedOverMusic;
- (void)setScreenSaverAllowedOverMusic:(BOOL)fp8;
- (id)parentalControlsPasscode;
- (void)setParentalControlsPasscode:(id)fp8;
- (int)parentalControlsYTMode;
- (void)setParentalControlsYTMode:(int)fp8;
- (id)photoDatabaseSourceDisplayString;
- (void)togglePhotoDatabaseSource;
- (id)photoXMLDatabaseSourceURL;
- (int)slideshowSecondsPerSlide;
- (void)setSlideshowSecondsPerSlide:(int)fp8;
- (BOOL)slideshowRepeat;
- (void)setSlideshowRepeat:(BOOL)fp8;
- (BOOL)slideshowShufflePhotos;
- (void)setSlideshowShufflePhotos:(BOOL)fp8;
- (BOOL)slideshowShuffleMusic;
- (void)setSlideshowShuffleMusic:(BOOL)fp8;
- (BOOL)slideshowPanAndZoom;
- (void)setSlideshowPanAndZoom:(BOOL)fp8;
- (BOOL)slideshowPlayMusic;
- (void)setSlideshowPlayMusic:(BOOL)fp8;
- (id)slideshowPlaylists;
- (id)slideshowSelectedPlaylistName;
- (void)setSlideshowSelectedPlaylistName:(id)fp8;
- (BOOL)slideshowUseNowPlayingMusic;
- (void)setSlideshowUseNowPlayingMusic:(BOOL)fp8;
- (id)slideshowTransitionNames;
- (id)slideshowSelectedTransitionName;
- (void)setSlideshowSelectedTransitionName:(id)fp8;
- (id)slideshowTransitionDirection;
- (void)setSlideshowTransitionDirection:(id)fp8;
- (BOOL)slideshowTransitionsDisabled;
- (BOOL)slideshowTransitionsRandom;
- (id)slideshowPlaybackOptions;
- (id)versionSoftware;
- (id)versionBuild;
- (BOOL)volumeEnabled;
- (float)systemVolume;
- (void)setSystemVolume:(float)fp8;
- (id)_ipConfig;
- (BOOL)syncIsSynced;
- (id)syncHostName;
- (BOOL)syncControlDisabled;
- (id)hwDeviceName;
- (BOOL)bootedFromRecoveryPartition;
- (BOOL)saveConfiguration:(id)fp8;

@end

