/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BRSingleton.h"
#import "BRControllerStack.h"

@class BRControllerStack;

@interface BRSentinel : BRSingleton
{
   id /* <BRMusicStoreImageDecryptionAgent> */ _musicStoreImageDecryptionAgent;
   id /* <BRDRMSyncAgent> */ _drmSyncAgent;
   id /* <BRSyncProgressAgent> */ _syncProgressAgent;
   id /* <BRYTSigningAgent> */ _signingAgent;
   id /* <BRRendererProvider> */ _rendererProvider;
   id /* <BRDAAPListenerEnabler> */ _daapListenerEnabler;
   BRControllerStack *_controllerStack;
   unsigned int _networkDependentControllerCount;
   BOOL _shouldAttemptDRMSync;
}

+ (id)singleton;
+ (void)setSingleton:(id)fp8;
- (id)init;
- (void)dealloc;
- (void)setMusicStoreImageDecryptionAgent:(id)fp8;
- (id)musicStoreImageDecryptionAgent;
- (void)setCurrentControllerStack:(id)fp8;
- (void)networkDependentControllerWillBePushed;
- (void)networkDependentControllerWasPopped;
- (void)setDRMSyncAgent:(id)fp8;
- (id)drmSyncAgent;
- (void)setSyncProgressAgent:(id)fp8;
- (id)syncProgressAgent;
- (void)setYTSigningAgent:(id)fp8;
- (id)YTSigningAgent;
- (void)setShouldAttemptDRMSync:(BOOL)fp8;
- (BOOL)shouldAttemptDRMSync;
- (void)setRendererProvider:(id)fp8;
- (id)rendererProvider;
- (void)setDAAPListenerEnabler:(id)fp8;
- (id)daapListenerEnabler;

@end

