/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BRController.h"

@class BRHeaderControl, BRTextControl, BRTextEntryControl;

/// \addtogroup BackRow

typedef enum {
    kFullKeyboardTextEntryStyle,
    kHexadecimalTextEntryStyle,
    kAlphaNumericTextEntryStyle,
} BRTextEntryStyle;

/// \ingroup BackRow
@interface BRTextEntryController : BRController
{
    BRTextEntryControl *_editor;
    BRHeaderControl *_header;
    BRTextControl *_prompt;
}

- (id)init;
- (id)initWithTextEntryStyle:(BRTextEntryStyle)style;
- (void)dealloc;
- (void)setTitle:(id)fp8;
- (void)setIcon:(id)fp8 horizontalOffset:(float)fp12 kerningFactor:(float)fp16;
- (void)setPromptText:(id)fp8;
- (void)setTextEntryTextFieldLabel:(id)fp8;
- (void)setTextEntryCompleteDelegate:(id)fp8;
- (void)setInitialTextEntryText:(id)fp8;
- (void)setShowUserEnteredText:(BOOL)fp8;
- (void)reset;
- (void)setDisplaysSelectionWidget:(BOOL)fp8;
- (BOOL)displaysSelectionWidget;

@end

