/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@class BRURLDocumentManager, NSError, NSMutableData, NSMutableDictionary, NSThread, NSURLConnection, NSURLRequest, NSURLResponse;

@interface BRURLDocument : NSObject
{
    NSURLRequest *_request;
    NSURLResponse *_response;
    NSError *_error;
    NSMutableData *_content;
    int _priority;
    BRURLDocumentManager *_manager;
    NSURLConnection *_connection;
    NSThread *_callingThread;
    NSMutableDictionary *_metadata;
}

+ (id)documentWithURLRequest:(id)fp8;
- (id)initWithURLRequest:(id)fp8;
- (id)init;
- (void)dealloc;
- (id)URLRequest;
- (id)URLResponse;
- (id)error;
- (id)content;
- (void)documentLoaded;
- (void)setMetadata:(id)fp8 forKey:(id)fp12;
- (id)metadataForKey:(id)fp8;

@end

