/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BRControl.h"

@class BRWaitSpinnerLayer;

/// \addtogroup BackRow

/// \ingroup BackRow
@interface BRWaitSpinnerControl : BRControl
{
    BRWaitSpinnerLayer *_layer;
}

- (id)init;
- (void)dealloc;
- (id)layer;
- (void)controlWasActivated;
- (void)controlWasDeactivated;

@end

