/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BRSingleton.h"

@interface RUISoundHandler : BRSingleton
{
    BOOL _isSoundEnabled;
    unsigned int _soundIDs[21];
}

+ (id)singleton;
+ (void)setSingleton:(id)fp8;
+ (void)playSound:(int)fp8;
+ (void)reloadSoundPreference;
- (id)init;
- (void)dealloc;

@end

